const actionTypes = {
  // All Products Types
  PRODUCTS_REQUEST_FETCH: "PRODUCTS_REQUEST_FETCH",
  PRODUCTS_REQUEST_SUCCESS: "PRODUCTS_REQUEST_SUCCESS",
  PRODUCTS_REQUEST_ERROR: "PRODUCTS_REQUEST_ERROR",

  // Fetch Single Product
  PRODUCT_REQUEST_FETCH: "PRODUCT_REQUEST_FETCH",
  PRODUCT_REQUEST_SUCCESS: "PRODUCT_REQUEST_SUCCESS",
  PRODUCT_REQUEST_ERROR: "PRODUCT_REQUEST_ERROR",

  // Shopping Cart
  CART_ADD_ITEM: "CART_ADD_ITEM",
  CART_REMOVE_ITEM: "CART_REMOVE_ITEM",
  CART_CLEAR_ITEM: "CART_CLEAR_ITEM",
  CART_DECREASE_ITEM_QTY: "CART_DECREASE_ITEM_QTY",
  CART_REMOVE_ALL_ITEMS: "CART_REMOVE_ALL_ITEMS",
  CART_SHIPPING_ADDRESS: "CART_SHIPPING_ADDRESS",
  CART_PAYMENT_METHOD: "CART_PAYMENT_METHOD",

  // User Login
  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_ERROR: "USER_LOGIN_ERROR",
  USER_LOGOUT: "USER_LOGOUT",

  // User Register
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_ERROR: "USER_REGISTER_ERROR",

  // User Details Types
  USER_DETAILS_REQUEST: "USER_DETAILS_REQUEST",
  USER_DETAILS_SCUCESS: "USER_DETAILS_SCUCESS",
  USER_DETAILS_ERROR: "USER_DETAILS_ERROR",

  // User Update Profile Types
  USER_UPDATE_PROFILE_REQUEST: "USER_UPDATE_PROFILE_REQUEST",
  USER_UPDATE_PROFILE_SCUCESS: "USER_UPDATE_PROFILE_SCUCESS",
  USER_UPDATE_PROFILE_ERROR: "USER_UPDATE_PROFILE_ERROR",

  // Order Items
  ORDER_ITEMS_REQUEST: "ORDER_ITEMS_REQUEST",
  ORDER_ITEMS_SUCCESS: "ORDER_ITEMS_SUCCESS",
  ORDER_ITEMS_ERROR: "ORDER_ITEMS_ERROR",

  GET_ORDER_DETAILS_REQUEST: "GET_ORDER_DETAILS_REQUEST",
  GET_ORDER_DETAILS_SUCCESS: "GET_ORDER_DETAILS_SUCCESS",
  GET_ORDER_DETAILS_ERROR: "GET_ORDER_DETAILS_SUCCESS",

  USER_ORDER_PAID_REQUEST: "USER_ORDER_PAID_REQUEST",
  USER_ORDER_PAID_SUCCESS: "USER_ORDER_PAID_SUCCESS",
  USER_ORDER_PAID_ERROR: "USER_ORDER_PAID_ERROR",
  USER_ORDER_PAID_RESET: "USER_ORDER_PAID_RESET",
};

export default actionTypes;
