const actionTypes = {
  // All Products Types
  PRODUCTS_REQUEST_FETCH: "PRODUCTS_REQUEST_FETCH",
  PRODUCTS_REQUEST_SUCCESS: "PRODUCTS_REQUEST_SUCCESS",
  PRODUCTS_REQUEST_ERROR: "PRODUCTS_REQUEST_ERROR",

  // Fetch Single Product
  PRODUCT_REQUEST_FETCH: "PRODUCT_REQUEST_FETCH",
  PRODUCT_REQUEST_SUCCESS: "PRODUCT_REQUEST_SUCCESS",
  PRODUCT_REQUEST_ERROR: "PRODUCT_REQUEST_ERROR",

  // Shopping Cart
  CART_ADD_ITEM: "CART_ADD_ITEM",
  CART_REMOVE_ITEM: "CART_REMOVE_ITEM",
  CART_CLEAR_ITEM: "CART_CLEAR_ITEM",
  CART_DECREASE_ITEM_QTY: "CART_DECREASE_ITEM_QTY",
  CART_REMOVE_ALL_ITEMS: "CART_REMOVE_ALL_ITEMS",
};

export default actionTypes;
